spring.application.name=ItCareerElevatorSixthExerciseOrderService

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/web_store_orders_db
spring.datasource.username=postgres
spring.datasource.password=PowerCell46
#spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=none

server.port=8082

# --- Snowflake id ---
snowflake.worker-id=4
snowflake.datacenter-id=11