spring.application.name=ItCareerElevatorSixthExerciseOrderService

server.port=8082

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/web_store_orders_db
spring.datasource.username=postgres
spring.datasource.password=PowerCell46
#spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=none

# --- KAFKA INFRASTRUCTURE CONFIGURATION ---
# Connection
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Producer/Serializer settings
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Custom App Topics
app.kafka.topics.reserve-items=reserveItems

# --- Snowflake id ---
snowflake.worker-id=4
snowflake.datacenter-id=11