spring.application.name=ItCareerElevatorThirdExerciseApiGateway

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/working_project_db
spring.datasource.username=postgres
spring.datasource.password=PowerCell46
spring.jpa.show-sql=true

# Stop the Spring banner from appearing
#spring.main.banner-mode=off

# Reduce logging level
#logging.level.root=warn

spring.jpa.hibernate.ddl-auto=create

# Format SQL output for better readability
spring.jpa.properties.hibernate.format_sql=true
# Statement logging with bind parameters
logging.level.org.hibernate.orm.jdbc.bind=trace

snowflake.worker-id=12
snowflake.datacenter-id=2

jwt.secret-key=qwAZS7TCtKxr6ahhUkVGp7lAcdiM98vl2/kzN4ZLJrYqIqdEJyIAZN6CxZJxM4VJ63kEY045TOJryI+c/ewY0w==