package com.ItCareerElevator.ItCareerElevatorFourthExerciseInvoiceMicroservice.repositories;

import com.ItCareerElevator.ItCareerElevatorFourthExerciseInvoiceMicroservice.entities.Order;
import com.ItCareerElevator.ItCareerElevatorFourthExerciseInvoiceMicroservice.utils.SoftDeleteRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface OrderRepository extends SoftDeleteRepository<Order, String> {
}
