spring.application.name=ItCareerElevatorFourthExerciseOrdersMicroservice

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/fitness_store_db
spring.datasource.username=postgres
spring.datasource.password=PowerCell46
    #spring.jpa.show-sql=true

# Stop the Spring banner from appearing
#spring.main.banner-mode=off

# Reduce logging level
#logging.level.root=warn

server.port=8081

spring.jpa.hibernate.ddl-auto=create

# Format SQL output for better readability
    #spring.jpa.properties.hibernate.format_sql=true
# Statement logging with bind parameters
    #logging.level.org.hibernate.orm.jdbc.bind=trace

spring.kafka.bootstrap-servers=localhost:9092

#app.kafka.topics.tweet=tweet

#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#spring.kafka.producer.properties.spring.json.add.type.headers=false