spring.application.name=ItCareerElevatorSixthExerciseApiGateway

server.port=8080

# --- DataSource ---
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/web_store_users_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:PowerCell46}
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create
# TODO: If it's none how is it gonna initialize the tables?
# spring.jpa.hibernate.ddl-auto=none

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.orm.jdbc.bind=trace

# --- Logging ---
#logging.level.root=warn

# --- Security / JWT ---
jwt.secret-key=${JWT_SECRET_KEY:qwAZS7TCtKxr6ahhUkVGp7lAcdiM98vl2/kzN4ZLJrYqIqdEJyIAZN6CxZJxM4VJ63kEY045TOJryI+c/ewY0w==}

# --- Microservice endpoints ---
users-microservice.base-endpoint=${USERS_MICROSERVICE_BASE_ENDPOINT:http://127.0.0.1:8081}
orders-microservice.base-endpoint=${ORDERS_MICROSERVICE_BASE_ENDPOINT:http://127.0.0.1:8082}
products-microservice.base-endpoint=${PRODUCTS_MICROSERVICE_BASE_ENDPOINT:http://127.0.0.1:8083}
