spring.application.name=ItCareerElevatorSixthExerciseMailService

server.port=8085

# --- Kafka ---
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.properties.spring.json.add.type.headers=false
logging.level.org.apache.kafka=WARN

spring.kafka.user-registered.group-id=${KAFKA_USER_REGISTERED_CONSUMER_GROUP:user_registered_mail_service}
spring.kafka.order-completed.group-id=${KAFKA_ORDER_COMPLETED_CONSUMER_GROUP:order_completed_mail_service}

app.kafka.topics.user-registered=userRegistered
app.kafka.topics.order-completed=orderCompleted

# --- Mail ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_EMAIL:placeholder}
spring.mail.password=${SPRING_MAIL_PASSWORD:placeholder}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true