spring.application.name=ItCareerElevatorSixthExercisePaymentService

server.port=8084

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/web_store_payments_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:PowerCell46}
#spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=create
# TODO: If it's none how is it gonna initialize the tables?
#spring.jpa.hibernate.ddl-auto=none

# --- KAFKA INFRASTRUCTURE CONFIGURATION ---
# Connection
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.items-reserved-consumer.group-id=${KAFKA_ITEMS_RESERVED_CONSUMER_GROUP:items_reserved_first_instance}

# Custom App Topics
app.kafka.topics.items-reserved=itemsReserved
app.kafka.topics.payment-successful=paymentSuccessful
app.kafka.topics.payment-unsuccessful=paymentUnsuccessful

# Alchemy/Infura URL
ethereum.node.url=${ETHEREUM_NODE_URL:https://eth-sepolia.g.alchemy.com/v2/YOUR_KEY}

ethereum-euro.ratio.url=https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=eur

# Your wallet address (where you receive payments)
ethereum.wallet.address=${ETHEREUM_WALLET_ADDRESS:0xYOUR_WALLET_ADDRESS}