spring.application.name=ItCareerElevatorSixthExerciseUserService

server.port=8081

# --- DataSource ---
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/web_store_users_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:PowerCell46}
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.orm.jdbc.bind=trace

# --- Logging ---
#logging.level.root=warn

# --- Kafka ---
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.kafka.topics.mail-register-user=mailRegisterUser

# --- Admin user ---
admin.username=PowerCell46
admin.email=makotsevo.fan@gmail.com
# Plain password: JsonobJeCT51
admin.password=$2a$10$8Ng.XShoXk3BS0QrkveLauwaHObE.9Q855EczneXBOAIUr6kBNTFa