spring.application.name=ItCareerElevatorSixthExerciseProductService

server.port=8083

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/web_store_products_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:PowerCell46}
#spring.jpa.show-sql=true

#spring.jpa.hibernate.ddl-auto=create
# TODO: If it's none how is it gonna initialize the tables?
spring.jpa.hibernate.ddl-auto=none

# --- Kafka ---
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.properties.spring.json.add.type.headers=false
logging.level.org.apache.kafka=WARN

spring.kafka.reserve-items-consumer.group-id=${KAFKA_RESERVE_ITEMS_CONSUMER_GROUP:reserve_items_product_service}
spring.kafka.payment-successful-consumer.group-id=${KAFKA_PAYMENT_SUCCESSFUL_CONSUMER_GROUP:payment_successful_product_service}
spring.kafka.payment-unsuccessful-consumer.group-id=${KAFKA_PAYMENT_UNSUCCESSFUL_CONSUMER_GROUP:payment_unsuccessful_product_service}

app.kafka.topics.reserve-items=reserveItems
app.kafka.topics.items-reserved=itemsReserved
app.kafka.topics.failure-reserve-items=failureReserveItems
app.kafka.topics.payment-successful=paymentSuccessful
app.kafka.topics.payment-unsuccessful=paymentUnsuccessful
app.kafka.topics.order-completed=orderCompleted

# --- Snowflake id ---
snowflake.worker-id=${SNOWFLAKE_WORKER_ID:2}
snowflake.datacenter-id=${SNOWFLAKE_DATA_CENTER_ID:3}
