spring.application.name=ItCareerElevatorSixthExerciseProductService

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/web_store_products_db
spring.datasource.username=postgres
spring.datasource.password=PowerCell46
spring.jpa.show-sql=true

server.port=8085

# --- Snowflake id ---
snowflake.worker-id=2
snowflake.datacenter-id=3