spring.application.name=ItCareerElevatorSixthExerciseProductService

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/web_store_products_db
spring.datasource.username=postgres
spring.datasource.password=PowerCell46
#spring.jpa.show-sql=true

#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=none

server.port=8083

# --- Snowflake id ---
snowflake.worker-id=2
snowflake.datacenter-id=3

# --- Kafka ---
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.consumer.group-id=${KAFKA_RESERVE_ITEMS_CONSUMER_GROUP:reserve_items_first_instance}
app.kafka.topics.reserve-items=reserveItems